### PR TITLE
Remove unnecessary code

### PR DESCRIPTION
**Pull request by melezhik**
Hi ! Pipeline should work without passing url explicitly as it already checkout out under source/ dir

HTH

Aleksei

### CODE REVIEW

**Comment by melezhik** [comment]
An example of successful build - https://ci.sparrowhub.io/report/2505

**Comment by melezhik** [comment]
I guess just this example mislead you - https://github.com/melezhik/SparrowCI/blob/main/examples/raku/zef.yaml , sorry , I am going to fix it , as it kinda obsolete

**Comment by rawleyfowler** [comment]
Thank you! Yeah sorry I am new to SparrowCI, thank you for developing it!

**Review by rawleyfowler — APPROVED** [review]

**Comment by melezhik** [comment]
Welcome and thank you for give it a try !

**Pull request merged**
